name: fleet_app
description: Aplikasi Manajemen Kendaraan Sewa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.0
  
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Storage
  flutter_secure_storage: ^9.0.0
  
  # Image
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # Navigation
  go_router: ^13.2.0
  
  # DI
  get_it: ^7.6.7
  
  # Utility
  intl: ^0.19.0
  
  # UI
  flutter_spinkit: ^5.2.0
  file_selector: ^1.0.3
  url_launcher: ^6.3.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
